### ISSUE TITLE
function list not working for Visual Foxpro on notepad++

### ISSUE THREAD

**Issue by ugurlu2001** [ToniKoehler/notepad-plus-plus-vfpLanguage#1]
Hello Toni,

I already using Visual Foxpro language on notepad++. I saw your "function list"  functionality today. I setup same instrudictions. But functionlist functionalities not working as aspected.

**Comment by ToniKoehler** [comment]
Hello Ugur,

notepad++ changed the functionlist functionality in version 7.9.1.
I updated the repository with new version, that works with latest Notepad++ Version (8.4.6).

**Comment by ugurlu2001** [comment]
Hello Toni,

Working like a charm :) 

Thank you for that useful functionalities on Notepad++ for Visual Foxpro :) 

https://www.foxite.com/archives/notepad-functionality-for-visual-foxpr-0000491801.htm

**Comment by ugurlu2001** [comment]
https://www.foxite.com/archives/notepad-functionality-for-visual-foxpr-0000491801.htm

**Comment by ToniKoehler** [comment]
Wellcome and thanks for sharing with our vfp community ;-)

**Comment by ugurlu2001** [comment]
You re wellcome Toni :)
